//! Subcommand handlers for the `outl` binary.

pub mod asset;
pub mod backlinks;
pub mod backup;
pub mod batch;
pub mod block;
pub mod daily;
pub mod doctor;
pub mod export;
pub mod export_v2;
pub mod history;
pub mod import;
pub mod init;
pub mod migrate_to_per_page_ops;
pub mod page;
pub mod plugin;
pub mod plugin_init;
pub mod plugin_source;
pub mod prop;
pub mod query;
pub mod reconcile;
pub mod recover;
pub mod search;
pub mod serve;
pub mod tag;
pub mod template;
pub mod theme;
pub mod workspace_info;
